apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app-namespace
data:
  DB_HOST: "postgres-service.db-namespace.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "messages_db"
  API_HOST: "0.0.0.0"
  API_PORT: "5000"

